# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'OCProject' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for OCProject
    pod 'MJRefresh'
    pod 'MJExtension'
    pod 'SDWebImage', '~> 4.0.0'
    pod 'AFNetworking', '~> 3.0'
    pod 'Masonry', '~> 1.0.2'
    pod 'pop', '~> 1.0'
    pod 'SVProgressHUD', '~> 2.0.3'
    pod 'SDCycleScrollView','~> 1.66'
    pod 'MMPopupView'
    pod 'IQKeyboardManager'

    # U-Share SDK UI模块（分享面板，建议添加）
    pod 'UMengUShare/UI'
    # 集成新浪微博
    pod 'UMengUShare/Social/Sina'
    # 集成微信
    pod 'UMengUShare/Social/WeChat'
    # 集成QQ
    pod 'UMengUShare/Social/QQ'

  target 'OCProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OCProjectUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
